#!/bin/bash

# set up local whisper.cpp and download model
echo "Cloning whisper.cpp repository..."
git clone https://github.com/ggerganov/whisper.cpp

echo "Changing directory to whisper.cpp..."
cd whisper.cpp

echo "Downloading the base English model..."
bash ./models/download-ggml-model.sh base.en

echo "Compiling the 'stream' executable..."
make stream

echo "Setup complete. You can now use the 'eavesdrop' command."
